name: Build macOS
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-10.15
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/macos/download-cairo.sh
      - run: ninja -f build-macos.ninja
      - run: |
          mkdir -p build/licenses/
          cp LICENSE.txt build/licenses/bismite-font-sheeter-LICENSE.txt
      - name: pack
        working-directory: ./build
        run: tar czf bismite-font-sheeter.tgz bin lib licenses
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bismite-font-sheeter.tgz
          asset_name: bismite-font-sheeter-macos.tgz
          tag: ${{ github.ref }}
          overwrite: true
