name: Build Linux
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libcairo2-dev ninja-build
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ninja
      - run: |
          mkdir -p build/licenses/
          cp LICENSE.txt build/licenses/bismite-font-sheeter-LICENSE.txt
      - name: pack
        working-directory: ./build
        run: tar czf bismite-font-sheeter.tgz bin licenses
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bismite-font-sheeter.tgz
          asset_name: bismite-font-sheeter-linux.tgz
          tag: ${{ github.ref }}
          overwrite: true
