name: Release Codepoints
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: tar zcf codepoints.tgz codepoints
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: codepoints.tgz
          asset_name: codepoints.tgz
          tag: ${{ github.ref }}
          overwrite: true
